package edu.team08.pacman.constants;

import java.util.HashMap;
import java.util.Map;

public class MovementConstants
{
    public static final float ENTITY_TELEPORT_MIN = 0f;
    public static final float ENTITY_TELEPORT_MAX = 19f;

    //TODO need to adjust speeds
    private static final float PACMAN_SPEED_LEVEL1_TO_LEVEL3 = 3.0f;
    private static final float PACMAN_SPEED_LEVEL4 = 3.2f;
    private static final float PACMAN_SPEED_LEVEL5_AND_UP = 3.4f;
    public static final Map<Integer, Float> LEVEL_TO_PACMAN_SPEED_MAP;
    static {
        LEVEL_TO_PACMAN_SPEED_MAP = new HashMap<>();
        LEVEL_TO_PACMAN_SPEED_MAP.put(1, PACMAN_SPEED_LEVEL1_TO_LEVEL3);
        LEVEL_TO_PACMAN_SPEED_MAP.put(2, PACMAN_SPEED_LEVEL1_TO_LEVEL3);
        LEVEL_TO_PACMAN_SPEED_MAP.put(3, PACMAN_SPEED_LEVEL1_TO_LEVEL3);
        LEVEL_TO_PACMAN_SPEED_MAP.put(4, PACMAN_SPEED_LEVEL4);
        LEVEL_TO_PACMAN_SPEED_MAP.put(5, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(6, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(7, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(8, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(9, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(10, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(11, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(12, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(13, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(14, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(15, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(16, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(17, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(18, PACMAN_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(19, PACMAN_SPEED_LEVEL5_AND_UP);
    }

    private static final float ALL_GHOST_SPEED_LEVEL1_TO_LEVEL2 = 2.8f;
    private static final float ALL_GHOST_SPEED_LEVEL3_TO_LEVEL4 = 3.0f;
    private static final float OTHER_GHOST_SPEED_LEVEL5_AND_UP = 3.2f;
    private static final float BLINKY_GHOST_SPEED_LEVEL5_AND_UP = 3.4f;
    public static final Map<Integer, Float> LEVEL_TO_NOTBLINKY_GHOST_SPEED_MAP;
    static {
        LEVEL_TO_NOTBLINKY_GHOST_SPEED_MAP = new HashMap<>();
        LEVEL_TO_PACMAN_SPEED_MAP.put(1, ALL_GHOST_SPEED_LEVEL1_TO_LEVEL2);
        LEVEL_TO_PACMAN_SPEED_MAP.put(2, ALL_GHOST_SPEED_LEVEL1_TO_LEVEL2);
        LEVEL_TO_PACMAN_SPEED_MAP.put(3, ALL_GHOST_SPEED_LEVEL3_TO_LEVEL4);
        LEVEL_TO_PACMAN_SPEED_MAP.put(4, ALL_GHOST_SPEED_LEVEL3_TO_LEVEL4);
        LEVEL_TO_PACMAN_SPEED_MAP.put(5, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(6, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(7, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(8, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(9, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(10, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(11, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(12, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(13, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(14, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(15, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(16, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(17, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(18, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(19, OTHER_GHOST_SPEED_LEVEL5_AND_UP);
    }
    public static final Map<Integer, Float> LEVEL_TO_BLINKY_SPEED_MAP;
    static {
        LEVEL_TO_BLINKY_SPEED_MAP = new HashMap<>();
        LEVEL_TO_PACMAN_SPEED_MAP.put(1, ALL_GHOST_SPEED_LEVEL1_TO_LEVEL2);
        LEVEL_TO_PACMAN_SPEED_MAP.put(2, ALL_GHOST_SPEED_LEVEL1_TO_LEVEL2);
        LEVEL_TO_PACMAN_SPEED_MAP.put(3, ALL_GHOST_SPEED_LEVEL3_TO_LEVEL4);
        LEVEL_TO_PACMAN_SPEED_MAP.put(4, ALL_GHOST_SPEED_LEVEL3_TO_LEVEL4);
        LEVEL_TO_PACMAN_SPEED_MAP.put(5, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(6, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(7, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(8, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(9, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(10, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(11, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(12, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(13, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(14, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(15, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(16, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(17, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(18, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
        LEVEL_TO_PACMAN_SPEED_MAP.put(19, BLINKY_GHOST_SPEED_LEVEL5_AND_UP);
    }

}
